### ISSUE TITLE
设置redis.pass了， 报 NOAUTH Authentication required.

### ISSUE THREAD

**Issue by ktzhush** [liukelin/canal_mysql_nosql_sync#18]
connect error!
Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.Jedis.rpush(Jedis.java:865)
	at canal.client.redis.push_redis(redis.java:37)
	at canal.client.CanalClientTest.printEntry(CanalClientTest.java:319)
	at canal.client.CanalClientTest.main(CanalClientTest.java:242)

**Comment by ktzhush** [comment]
Jedis jedis = new Jedis(host, port);
        jedis.auth(pass);

改好了。不报错了。

**Comment by liukelin** [comment]
恩恩
